#pragma once

enum err_code {
	ERR_NONE,
	ERR_NUM_INVALID,
	ERR_PTC_COMMAND_INVALID,
	ERR_PTC_FUNCTION_INVALID,
	ERR_PTC_OPERATOR_INVALID,
	ERR_INVALID_BC,
	ERR_VARIABLE_CREATION_FAIL,
	ERR_PRINT_INVALID_OP,
	ERR_PRINT_INVALID_STACK,
	ERR_OP_DIFFERENT_TYPES,
	ERR_UNIMPLEMENTED,
	ERR_OP_INVALID_TYPES,
	ERR_OP_INVALID_TYPE,
	ERR_OP_ASSIGN_TO_LITERAL,
	ERR_OP_ASSIGN_INVALID_TYPE,
	ERR_NEXT_WITHOUT_FOR,
	ERR_MISSING_OP_ASSIGN_FOR,
	ERR_MISSING_ELSE_AND_ENDIF,
};

extern const char * error_messages[];
